--- #YAML:1.0
name: Module-Packaged
version: 0.74
license: perl
distribution_type: module
requires:
  Cache::Cache: 1.02
  IO::File: 1.08
  IO::Zlib: 1.01
  LWP::Simple: 1.38
  Parse::CPAN::Packages: 2.20
  Parse::Debian::Packages: 0.01
  Sort::Versions: 1.50
  Test::More: 0.47
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Module::Packaged:
    file: lib/Module/Packaged.pm
    version: 0.74
generated_by: Module::Build version 0.21
