--- #YAML:1.0
name: Module-Packaged
version: 0.34
license: perl
distribution_type: module
requires:
  CPAN::DistnameInfo: 0.03
  File::Slurp: 2004.0904
  IO::File: 1.08
  IO::Zlib: 1.01
  LWP::Simple: 1.38
  Sort::Versions: 1.50
  Test::More: 0.47
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Module::Packaged:
    file: lib/Module/Packaged.pm
    version: 0.34
generated_by: Module::Build version 0.21
